# Generated by Django 5.2.14 on 2026-05-15 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BicingEstacio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("capacity", models.IntegerField()),
                ("bikes_available", models.IntegerField()),
                ("docks_available", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Conversa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creada_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_location", models.CharField(max_length=200)),
                ("end_location", models.CharField(max_length=200)),
                ("distance", models.FloatField()),
                ("air_quality", models.FloatField()),
                ("is_safe", models.BooleanField(default=True)),
                ("route_points", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="TemplateExercici",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("descripcio", models.TextField(blank=True)),
                (
                    "tipusExercici",
                    models.CharField(
                        choices=[
                            ("CAM", "Caminar"),
                            ("BIC", "Bici"),
                            ("ALT", "Altres"),
                        ],
                        default="CAM",
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Titol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("descripcio", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="AirQualityHistoric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("aqi", models.FloatField()),
                ("day_of_week", models.IntegerField()),
                ("hora", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("lat", "lon", "day_of_week", "hora")},
            },
        ),
        migrations.CreateModel(
            name="PlaEntrenament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diesDurada", models.IntegerField()),
                ("numEntrenamentsSetmanals", models.IntegerField()),
                (
                    "templates",
                    models.ManyToManyField(
                        blank=True, related_name="plans", to="core.templateexercici"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "google_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("punts", models.IntegerField()),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics"),
                ),
                ("teBici", models.BooleanField(default=False)),
                ("pes", models.FloatField()),
                ("altura", models.FloatField()),
                ("ratxa", models.IntegerField()),
                (
                    "dificultatPla",
                    models.CharField(
                        choices=[
                            ("REL", "Relaxat"),
                            ("NOR", "Normal"),
                            ("INT", "Intens"),
                        ],
                        default="NOR",
                        max_length=3,
                    ),
                ),
                (
                    "idioma",
                    models.CharField(
                        choices=[
                            ("CAT", "Catalan"),
                            ("ES", "Español"),
                            ("ENG", "English"),
                        ],
                        default="ES",
                        max_length=3,
                    ),
                ),
                ("limitRutes", models.IntegerField()),
                ("titol", models.CharField(blank=True, max_length=100)),
                (
                    "insignies",
                    models.ImageField(blank=True, null=True, upload_to="insignies"),
                ),
                ("fcm_token", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "plans",
                    models.ManyToManyField(
                        blank=True, related_name="usuaris", to="core.plaentrenament"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Missatge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contingut", models.TextField()),
                ("enviat_at", models.DateTimeField(auto_now_add=True)),
                ("llegit", models.BooleanField(default=False)),
                (
                    "conversa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missatges",
                        to="core.conversa",
                    ),
                ),
                (
                    "emissor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missatges_enviats",
                        to="core.usuari",
                    ),
                ),
            ],
            options={
                "ordering": ["enviat_at"],
            },
        ),
        migrations.CreateModel(
            name="Forum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("descripcio", models.CharField(blank=True, max_length=500)),
                ("creat_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creat_per",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forums_creats",
                        to="core.usuari",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exercici",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance_meters", models.FloatField(default=0.0)),
                ("duration_seconds", models.IntegerField(default=0)),
                ("avg_speed_kmh", models.FloatField(default=0.0)),
                ("route_points", models.JSONField(default=list)),
                ("dataIni", models.DateTimeField(blank=True, null=True)),
                (
                    "sensacio",
                    models.CharField(
                        choices=[
                            ("MBE", "Molt bé"),
                            ("BE", "bé"),
                            ("NOR", "Normal"),
                            ("CA", "Cansat"),
                            ("MCA", "Molt cansat"),
                        ],
                        default="NOR",
                        max_length=3,
                    ),
                ),
                ("comentari_sensacio", models.TextField(blank=True, null=True)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercicis",
                        to="core.templateexercici",
                    ),
                ),
                (
                    "usuari",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercicis",
                        to="core.usuari",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="conversa",
            name="usuari_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="converses_com_1",
                to="core.usuari",
            ),
        ),
        migrations.AddField(
            model_name="conversa",
            name="usuari_2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="converses_com_2",
                to="core.usuari",
            ),
        ),
        migrations.CreateModel(
            name="ForumFavorit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("afegit_at", models.DateTimeField(auto_now_add=True)),
                (
                    "forum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorits",
                        to="core.forum",
                    ),
                ),
                (
                    "usuari",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forums_favorits",
                        to="core.usuari",
                    ),
                ),
            ],
            options={
                "unique_together": {("usuari", "forum")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="conversa",
            unique_together={("usuari_1", "usuari_2")},
        ),
        migrations.CreateModel(
            name="Amistat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estat",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendent"),
                            ("ACC", "Acceptada"),
                            ("REJ", "Rebutjada"),
                        ],
                        default="PEN",
                        max_length=3,
                    ),
                ),
                ("creat_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receptor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amistats_rebudes",
                        to="core.usuari",
                    ),
                ),
                (
                    "solicitant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amistats_enviades",
                        to="core.usuari",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("solicitant", models.F("receptor")), _negated=True
                        ),
                        name="no_self_friendship",
                    )
                ],
                "unique_together": {("solicitant", "receptor")},
            },
        ),
        migrations.CreateModel(
            name="UsuariRuta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.route"
                    ),
                ),
                (
                    "usuari",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rutes_guardades",
                        to="core.usuari",
                    ),
                ),
            ],
            options={
                "unique_together": {("usuari", "route")},
            },
        ),
        migrations.CreateModel(
            name="UsuariTitol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.titol"
                    ),
                ),
                (
                    "usuari",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="titols_desbloquejats",
                        to="core.usuari",
                    ),
                ),
            ],
            options={
                "unique_together": {("usuari", "titol")},
            },
        ),
    ]
