# Generated by Django 5.2.13 on 2026-04-19 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BicingEstacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('capacity', models.IntegerField()),
                ('bikes_available', models.IntegerField()),
                ('docks_available', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Titol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('descripcio', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='usuari',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuari',
            name='titol',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='AirQualityHistoric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('aqi', models.FloatField()),
                ('day_of_week', models.IntegerField()),
                ('hora', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('lat', 'lon', 'day_of_week', 'hora')},
            },
        ),
        migrations.CreateModel(
            name='UsuariRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutes_guardades', to='core.usuari')),
            ],
            options={
                'unique_together': {('usuari', 'route')},
            },
        ),
        migrations.CreateModel(
            name='UsuariTitol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.titol')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titols_desbloquejats', to='core.usuari')),
            ],
            options={
                'unique_together': {('usuari', 'titol')},
            },
        ),
    ]
