# Generated by Django 5.2.13 on 2026-04-29 18:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_bicingestacio_titol_usuari_google_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercici",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataInici", models.DateTimeField(default=django.utils.timezone.now)),
                ("dataFi", models.DateTimeField(blank=True, null=True)),
                ("completat", models.BooleanField(default=False)),
                (
                    "tipusExercici",
                    models.CharField(
                        choices=[
                            ("CAM", "Caminar"),
                            ("BIC", "Bici"),
                            ("ALT", "Altres"),
                        ],
                        default="CAM",
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaEntrenament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diesDurada", models.IntegerField()),
                ("numEntrenamentsSetmanals", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TemplateExercici",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("descripcio", models.TextField(blank=True)),
                (
                    "tipusExercici",
                    models.CharField(
                        choices=[
                            ("CAM", "Caminar"),
                            ("BIC", "Bici"),
                            ("ALT", "Altres"),
                        ],
                        default="CAM",
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="usuari",
            name="dificultatPla",
            field=models.CharField(
                choices=[("REL", "Relaxat"), ("NOR", "Normal"), ("INT", "Intens")],
                default="NOR",
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="ExerciciExterior",
            fields=[
                (
                    "exercici_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.exercici",
                    ),
                ),
                ("dist_feta_km", models.FloatField()),
                ("calories", models.FloatField()),
            ],
            bases=("core.exercici",),
        ),
        migrations.AddField(
            model_name="usuari",
            name="plans",
            field=models.ManyToManyField(
                blank=True, related_name="usuaris", to="core.plaentrenament"
            ),
        ),
        migrations.AddField(
            model_name="plaentrenament",
            name="templates",
            field=models.ManyToManyField(
                related_name="plans", to="core.templateexercici"
            ),
        ),
        migrations.AddField(
            model_name="exercici",
            name="template_origen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instancies_exercici",
                to="core.templateexercici",
            ),
        ),
        migrations.CreateModel(
            name="ExerciciRuta",
            fields=[
                (
                    "exerciciexterior_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.exerciciexterior",
                    ),
                ),
                ("dist_objectiu_km", models.FloatField()),
            ],
            bases=("core.exerciciexterior",),
        ),
    ]
