# Generated by Django 5.2.13 on 2026-04-30 14:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_exercici_plaentrenament_templateexercici_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exerciciruta",
            name="exerciciexterior_ptr",
        ),
        migrations.RemoveField(
            model_name="exercici",
            name="completat",
        ),
        migrations.RemoveField(
            model_name="exercici",
            name="dataFi",
        ),
        migrations.RemoveField(
            model_name="exercici",
            name="dataInici",
        ),
        migrations.RemoveField(
            model_name="exercici",
            name="template_origen",
        ),
        migrations.RemoveField(
            model_name="exercici",
            name="tipusExercici",
        ),
        migrations.AddField(
            model_name="exercici",
            name="avg_speed_kmh",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="exercici",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exercici",
            name="distance_meters",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="exercici",
            name="duration_seconds",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exercici",
            name="route_points",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="exercici",
            name="usuari",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercicis",
                to="core.usuari",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ExerciciExterior",
        ),
        migrations.DeleteModel(
            name="ExerciciRuta",
        ),
    ]
