# Generated by Django 5.2.13 on 2026-04-30 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_exerciciruta_exerciciexterior_ptr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercici",
            name="completat",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exercici",
            name="dataInici",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exercici",
            name="distanciaFeta",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="exercici",
            name="distanciaObjectiu",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="exercici",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instancies_exercici",
                to="core.templateexercici",
            ),
        ),
    ]
