# Generated by Django 5.2.12 on 2026-05-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_exercici_completat_exercici_datainici_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="route_points",
            field=models.JSONField(default=list),
        ),
    ]
