# Generated by Django 5.2.14 on 2026-05-08 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_route_route_points"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amistat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estat",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendent"),
                            ("ACC", "Acceptada"),
                            ("REJ", "Rebutjada"),
                        ],
                        default="PEN",
                        max_length=3,
                    ),
                ),
                ("creat_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receptor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amistats_rebudes",
                        to="core.usuari",
                    ),
                ),
                (
                    "solicitant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amistats_enviades",
                        to="core.usuari",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("solicitant", models.F("receptor")), _negated=True
                        ),
                        name="no_self_friendship",
                    )
                ],
                "unique_together": {("solicitant", "receptor")},
            },
        ),
    ]
