# Generated by Django 5.2.14 on 2026-05-11 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_amistat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creada_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuari_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="converses_com_1",
                        to="core.usuari",
                    ),
                ),
                (
                    "usuari_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="converses_com_2",
                        to="core.usuari",
                    ),
                ),
            ],
            options={
                "unique_together": {("usuari_1", "usuari_2")},
            },
        ),
        migrations.CreateModel(
            name="Missatge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contingut", models.TextField()),
                ("enviat_at", models.DateTimeField(auto_now_add=True)),
                ("llegit", models.BooleanField(default=False)),
                (
                    "conversa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missatges",
                        to="core.conversa",
                    ),
                ),
                (
                    "emissor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missatges_enviats",
                        to="core.usuari",
                    ),
                ),
            ],
            options={
                "ordering": ["enviat_at"],
            },
        ),
    ]
