# Generated by Django 5.2.14 on 2026-05-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_conversa_missatge"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuari",
            name="fcm_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
