# Generated by Django 5.2.14 on 2026-05-14 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_exercici_created_at_and_more'),
        ('core', '0009_usuari_fcm_token'),
    ]

    operations = [
    ]
