# Generated by Django 5.2.14 on 2026-05-13 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_usuari_fcm_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="Insignia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("descripcio", models.TextField()),
                (
                    "icona",
                    models.ImageField(
                        blank=True, null=True, upload_to="insignies_icons/"
                    ),
                ),
                ("tipus", models.CharField(max_length=50)),
                ("valor_requerit", models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name="usuari",
            name="insignies",
        ),
        migrations.CreateModel(
            name="UsuariInsignia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insignia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.insignia"
                    ),
                ),
                (
                    "usuari",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insignies_guanyades",
                        to="core.usuari",
                    ),
                ),
            ],
            options={
                "unique_together": {("usuari", "insignia")},
            },
        ),
    ]
