# Generated by Django 5.2.14 on 2026-05-14 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_usuari_fcm_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("descripcio", models.CharField(blank=True, max_length=500)),
                ("creat_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creat_per",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forums_creats",
                        to="core.usuari",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ForumFavorit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("afegit_at", models.DateTimeField(auto_now_add=True)),
                (
                    "forum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorits",
                        to="core.forum",
                    ),
                ),
                (
                    "usuari",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forums_favorits",
                        to="core.usuari",
                    ),
                ),
            ],
            options={
                "unique_together": {("usuari", "forum")},
            },
        ),
    ]
