# Generated by Django 5.2.14 on 2026-05-14 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20260514_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercici',
            name='completat',
        ),
        migrations.RemoveField(
            model_name='exercici',
            name='dataInici',
        ),
        migrations.RemoveField(
            model_name='exercici',
            name='distanciaFeta',
        ),
        migrations.RemoveField(
            model_name='exercici',
            name='distanciaObjectiu',
        ),
    ]
