# Generated by Django 5.2.14 on 2026-05-14 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_insignia_remove_usuari_insignies_usuariinsignia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="insignia",
            name="icona",
        ),
        migrations.AddField(
            model_name="insignia",
            name="nom_icona",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="usuari",
            name="ultima_activitat",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PuntLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantitat", models.IntegerField()),
                ("motiu", models.CharField(max_length=255)),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "usuari",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs_punts",
                        to="core.usuari",
                    ),
                ),
            ],
        ),
    ]
