# Generated by Django 5.2.14 on 2026-05-17 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_forum_forumfavorit"),
        ("core", "0011_remove_insignia_icona_insignia_nom_icona_and_more"),
    ]

    operations = []
