# Generated by Django 5.2.14 on 2026-05-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_forum_forumfavorit"),
        ("core", "0011_remove_exercici_completat_remove_exercici_datainici_and_more"),
    ]

    operations = []
