# Generated by Django 5.2.14 on 2026-05-17 20:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_merge_20260517_2244"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="insignia",
            name="nom_icona",
        ),
        migrations.AddField(
            model_name="insignia",
            name="icona",
            field=models.ImageField(blank=True, null=True, upload_to="insignies"),
        ),
        migrations.AddField(
            model_name="usuariinsignia",
            name="data_guanyada",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
