# Generated by Django 5.2.14 on 2026-05-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_insignia_nom_icona_insignia_icona_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercici",
            name="comentari",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="exercici",
            name="sensacio",
            field=models.CharField(
                choices=[
                    (1, "Molt Malament"),
                    (2, "Malament"),
                    (3, "Normal"),
                    (4, "Be"),
                    (5, "Molt Be"),
                ],
                default=3,
                max_length=3,
            ),
        ),
    ]
