# Generated by Django 5.2.14 on 2026-05-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_exercici_comentari_exercici_sensacio"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuari",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
