# Generated by Django 5.2.14 on 2026-05-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_usuari_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectiuExercici",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[("OR", "Or"), ("PLA", "Plata"), ("BRO", "Bronze")],
                        default="BRO",
                        max_length=3,
                    ),
                ),
                ("descripcio", models.TextField(blank=True)),
                ("recompensa", models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="exercici",
            name="distanciaObjectiu",
        ),
        migrations.AddField(
            model_name="exercici",
            name="objectius",
            field=models.ManyToManyField(
                blank=True,
                related_name="exercicis_asociats",
                to="core.objectiuexercici",
            ),
        ),
    ]
