# Generated by Django 5.2.14 on 2026-05-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_objectiuexercici_remove_exercici_distanciaobjectiu_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercici",
            name="medalla_obtinguda",
            field=models.CharField(
                blank=True,
                choices=[("OR", "Or"), ("PLA", "Plata"), ("BRO", "Bronze")],
                max_length=3,
                null=True,
            ),
        ),
    ]
