# Generated by Django 5.2.14 on 2026-05-21 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_exercici_medalla_obtinguda"),
    ]

    operations = [
        migrations.CreateModel(
            name="MissioPermanent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("descripcio", models.TextField(blank=True)),
                ("recompensa", models.IntegerField(default=0)),
                (
                    "metrica",
                    models.CharField(
                        choices=[
                            ("DIST_CAM", "Distancia total caminar (km)"),
                            ("DIST_BIC", "Distancia total bici (km)"),
                            ("TOTAL_EXE", "Nombre d'exercicis totals"),
                            ("MED_PLA_OR", "Nombre de medalles de plata o superior"),
                            ("MED_OR", "Nombre de medalles d'or"),
                            (
                                "MAX_DIST_CAM",
                                "Màxima distància d'una ruta caminant (km)",
                            ),
                            (
                                "MAX_DIST_BIC",
                                "Màxima distància d'una ruta en bici (km)",
                            ),
                            ("MAX_TEMPS", "Màxim temps d'una ruta (h)"),
                        ],
                        max_length=15,
                    ),
                ),
                ("fase_metrica", models.IntegerField(default=1)),
                ("valor_objectiu", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="MissioUsuari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completada", models.BooleanField(default=False)),
                (
                    "missio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions_usuari",
                        to="core.missiopermanent",
                    ),
                ),
                (
                    "usuari",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions_usuari",
                        to="core.usuari",
                    ),
                ),
            ],
        ),
    ]
