# Generated by Django 5.2.14 on 2026-05-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_exercici_medalla_obtinguda"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercici",
            name="objectius",
        ),
        migrations.RemoveField(
            model_name="exercici",
            name="comentari",
        ),
        migrations.RemoveField(
            model_name="exercici",
            name="medalla_obtinguda",
        ),
        migrations.RemoveField(
            model_name="exercici",
            name="sensacio",
        ),
        migrations.RemoveField(
            model_name="usuari",
            name="is_active",
        ),
        migrations.AddField(
            model_name="exercici",
            name="distanciaObjectiu",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="titol",
            name="punts_minims",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usuari",
            name="titols_pendents",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usuari",
            name="ultim_milestone_titols",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="ObjectiuExercici",
        ),
    ]
