# Generated by Django 5.2.14 on 2026-05-21 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_titol_punts_minims_usuari_titols_pendents_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MissatgeForum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contingut", models.TextField()),
                ("enviat_at", models.DateTimeField(auto_now_add=True)),
                (
                    "emissor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missatges_forum_enviats",
                        to="core.usuari",
                    ),
                ),
                (
                    "forum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missatges",
                        to="core.forum",
                    ),
                ),
            ],
            options={
                "ordering": ["enviat_at"],
            },
        ),
    ]
