# Generated by Django 5.2.14 on 2026-05-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_missatgeforum"),
    ]

    operations = [
        migrations.AddField(
            model_name="plaentrenament",
            name="diesSetmana",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="plaentrenament",
            name="esport",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plaentrenament",
            name="nivell",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="plaentrenament",
            name="diesDurada",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="plaentrenament",
            name="numEntrenamentsSetmanals",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="plaentrenament",
            name="templates",
            field=models.ManyToManyField(
                blank=True, related_name="plans", to="core.templateexercici"
            ),
        ),
    ]
