# Generated by Django 5.2.14 on 2026-05-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_missatgeforum"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="end_address",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AddField(
            model_name="route",
            name="start_address",
            field=models.CharField(default="", max_length=300),
        ),
    ]
