# Generated by Django 5.2.14 on 2026-05-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_plaentrenament_diessetmana_plaentrenament_esport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plaentrenament",
            name="dataFi",
            field=models.DateField(blank=True, null=True),
        ),
    ]
