# Generated by Django 5.2.14 on 2026-05-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_plaentrenament_datafi"),
    ]

    operations = [
        migrations.AddField(
            model_name="templateexercici",
            name="dificutat",
            field=models.CharField(
                choices=[
                    ("PRI", "Principiant"),
                    ("INT", "Intermedi"),
                    ("AVA", "Avançat"),
                ],
                default="PRI",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="templateexercici",
            name="tipusExercici",
            field=models.CharField(
                choices=[("CAM", "Caminar"), ("BIC", "Bici")],
                default="CAM",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="usuari",
            name="dificultatPla",
            field=models.CharField(
                choices=[
                    ("PRI", "Principiant"),
                    ("INT", "Intermedi"),
                    ("AVA", "Avançat"),
                ],
                default="INT",
                max_length=3,
            ),
        ),
    ]
