# Generated by Django 5.2.14 on 2026-05-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_route_end_address_route_start_address"),
        ("core", "0022_templateexercici_dificutat_and_more"),
    ]

    operations = []
