# Generated by Django 5.2.14 on 2026-05-24 20:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_route_end_address_route_start_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="end_address",
        ),
        migrations.RemoveField(
            model_name="route",
            name="start_address",
        ),
        migrations.AddField(
            model_name="exercici",
            name="pla",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plans_entrenament",
                to="core.plaentrenament",
            ),
        ),
        migrations.AddField(
            model_name="plaentrenament",
            name="actiu",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plaentrenament",
            name="dataInici",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="plaentrenament",
            name="usuari",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plans_entrenament",
                to="core.usuari",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="plaentrenament",
            name="diesDurada",
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name="plaentrenament",
            name="diesSetmana",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Llista de dies [1, 2, 4] (1=Dilluns)",
            ),
        ),
        migrations.AlterField(
            model_name="plaentrenament",
            name="esport",
            field=models.CharField(
                choices=[("CAM", "Caminar"), ("BIC", "Bici")],
                default="CAM",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="plaentrenament",
            name="nivell",
            field=models.IntegerField(default=1, help_text="1: PRI, 2: INT, 3: AVA"),
            preserve_default=False,
        ),
    ]
