# Generated by Django 5.2.14 on 2026-05-24 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_exercici_pla_plaentrenament_actiu_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plaentrenament",
            name="nivell",
            field=models.IntegerField(default=1, help_text="1: PRI, 2: INT, 3: AVA"),
        ),
        migrations.AlterField(
            model_name="plaentrenament",
            name="usuari",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plans_entrenament",
                to="core.usuari",
            ),
        ),
    ]
