# Generated by Django 5.2.14 on 2026-05-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_exercici_pla_plaentrenament_actiu_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plaentrenament",
            name="nom",
            field=models.CharField(default="", max_length=100),
        ),
    ]
